### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by multimeric** [hanjinliu/macro-kit#4]
The recent release of 0.4.7 broke my build in Python 3.8:

```
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/macrokit/__init__.py:8: in <module>
    from macrokit.expression import (
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/macrokit/expression.py:224: in <module>
    class Expr:
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/macrokit/expression.py:411: in Expr
    cls, fn: "_Expr", args: tuple[_Expr, ...], kwargs: dict[str, _Expr]
E   TypeError: 'type' object is not subscriptable
```

You're indexing a type:
https://github.com/hanjinliu/macro-kit/blob/b0764e16da0cdf626e8c129fcf05891681f6d5f0/macrokit/expression.py#L411

But also supporting Python 3.8:
https://github.com/hanjinliu/macro-kit/blob/b0764e16da0cdf626e8c129fcf05891681f6d5f0/pyproject.toml#L11

**Comment by hanjinliu** [comment]
Thanks! Sorry for the inconvenience.
New version will be uploaded later.
